// Map of custom emojis to search keywords for high-accuracy searches
export const EMOJI_NAMES_MAP: Record<string, string> = {
  // --- Smileys & Emotions ---
  "😀": "grinning face happy smile joy laugh",
  "😃": "smiley happy open mouth smile joy laugh",
  "😄": "smile happy squinting eyes grin joy laugh",
  "😁": "beaming face grinning teeth smile happy",
  "😆": "laughing squinting face laugh smile happy",
  "😅": "sweat smile embarrassed relieved lucky happy",
  "😂": "cry laugh tears of joy laughing funny lol",
  "🤣": "rofl rolling on floor laughing funny lol",
  "😊": "smile smiling face blushing cheeks warm happy sweet",
  "😇": "halo innocent angel holy good blessed",
  "🙂": "slightly smiling happy normal friendly",
  "🙃": "upside down silly goofy sarcasm flip",
  "😉": "wink winking face friendly playful tease",
  "😌": "relieved content peaceful calm zen quiet",
  "😍": "heart eyes love adore beautiful cute crush",
  "🥰": "hearts blushing in love sweet adored cared affection",
  "😘": "kiss blow kiss loving heart romantic sweet",
  "😗": "kissing face friendly soft",
  "😙": "kissing smiling eyes friendly",
  "😚": "kissing closed eyes warm friendly",
  "😋": "yum delicious tasty food hungry tongue out",
  "😛": "tongue out playful cheeky goofy",
  "😝": "squinting tongue out playful cheeky crazy goofy",
  "😜": "winking tongue out playful cheeky crazy goofy",
  "🤪": "zany face crazy wild goofy silly eye",
  "🤨": "raised eyebrow questioning skeptic curious unsure disapproval",
  "🧐": "monocle classy inspect detective investigate fancy look",
  "🤓": "nerd geek smart study books glasses tech",
  "😎": "cool sunglasses chill awesome style radical",
  "🥸": "disguise spy mask anonymous hide secret",
  "🤩": "star struck amazed wow star excellent celebrity",
  "🥳": "partying face horn celebration birthday festive cheer dance",
  "😏": "smirk sly playful teasing confident cheeky",
  "😒": "unamused unhappy bored annoyed meh disapproval",
  "😞": "disappointed sad downcast sorry bad unhappy",
  "😔": "pensive sad depressed sorrow thoughtful lonely",
  "😟": "worried anxious concerned uneasy afraid nervous",
  "😕": "confused puzzled face unspeakable unsure",
  "🙁": "slightly frowning sad unhappy normal",
  "☹️": "frowning sad unhappy upset cry",
  "😣": "persevere struggling pain hard stress",
  "😖": "confounded annoyed stressed upset",
  "😫": "tired exhausted sleep weary yawn",
  "😩": "weary tired upset crying pleading screaming",
  "🥺": "pleading puppy eyes Begging cute sad mercy",
  "😢": "crying tear sad crying tear unhappy upset weep",
  "😭": "loudly crying bawling drama weeping sad upset sob",
  "😤": "steam from nose angry win triumph determined proud",
  "😠": "angry mad upset annoyed furious grumpy",
  "😡": "pouting angry furious mad red face",
  "🤬": "swearing cursing angry swearing mouth symbols curse",
  "🤯": "mind blown exploding head shocked amazing awesome mindblown",
  "😳": "flushed embarrassed shocked wide eyes alert blushing",
  "🥵": "hot red fever warm summer sweaty thirsty heat",
  "Cold": "cold blue frozen ice weather winter shiver",
  "🥶": "cold frozen ice chill temperature blue face",
  "😱": "screaming fear shocked ghost scream terrified afraid scared",
  "😨": "fearful scared afraid shocked concerned terrified",
  "😰": "anxious blue forehead cold sweat fear worried stressed",
  "😥": "sad relieved droplet tear stress lucky",
  "😓": "cold sweat downcast forehead sweat stress try worry",
  "🤗": "hug hugging welcoming friendly open arms warm",
  "🤔": "thinking pondering deep wondering query question hmm",
  "🫣": "peeking eye hide scary peek look coward",
  "🤭": "giggle hand over mouth secret gossip oops",
  "🫢": "gasp open mouth shock hand over mouth surprize surprise",
  "🤫": "shh quiet silence secret whisper hush",
  "🫠": "melting hot heat warm summer dissolve",
  "🤥": "lying pinocchio liar long nose fake",
  "😶": "no mouth speechless quiet silent empty",
  "😐": "neutral neutral face simple blank pokerface meh",
  "😑": "expressionless bored tired flat look squinting pokerface",
  "😬": "grimacing cringe awkward oops teeth error tense",
  "🫨": "shaking face dynamic shock vibration dizzy alert",
  "🙄": "rolling eyes annoyed sarcasm bored whatever eye-roll",
  "😯": "hushed shocked surprised wonder wait",
  "😦": "frowning open mouth surprised sad shock concerned",
  "😧": "anguished sad shocked pain afraid worried",
  "😮": "open mouth shocked wow surprised wonder",
  "😲": "astonished amazed shocked extreme wow surprise",
  "🥱": "yawning tired sleepy lazy bored bedtime",
  "😴": "sleeping zzz beds sleepy tired rest snoring",
  "🤤": "drooling tasty yummy hungry sleep desire saliva",
  "😪": "sleepy bubble tired sleep rest lazy",
  "😵": "dizzy crossed eyes shock dead faint knock out",
  "😵‍💫": "dizzy spiral eyes spin dizzy hypnotic confused lost",
  "🤐": "zipper mouth silent quiet secret hush zipped",
  "🥴": "woozy drunk dizzy sick wavy face tipsy",
  "🤢": "nauseated green sick vomit disgust gross",
  "🤮": "vomiting puke throwing up barf sick green",
  "🤧": "sneezing cold tissue flu sick allergy snort",
  "😷": "mask medical doctor patient sick COVID contagion",
  "🤒": "thermometer fever sick hot ill hospital warmth",
  "🤕": "head bandage hurt injury accident sick hospital pain",
  "🤑": "money mouth rich cash wealth dollar green face",
  "🤠": "cowboy hat ranger rodeo western horse country",
  "😈": "smiling devil purple evil demon horns mischief",
  "👿": "angry devil purple demon horns anger evil",
  "👹": "ogre red monster scary mask halloween demon",
  "👺": "goblin red long nose monster mask japanese",
  "🤡": "clown makeup funny birthday circus joker jester",
  "💩": "poop turd brown smiling stinky crappy piece",
  "Ghost": "ghost spooky monster white floating halloween",
  "👻": "ghost spooky white halloween cute scary",
  "💀": "skull dead death bone gothic scary skeleton",
  "☠️": "pirate skull danger hazard poisonous crossbones",
  "👽": "alien outer space mars extraterrestrial scifi UFO",
  "👾": "alien monster game arcade pixel retro space invader",
  "🤖": "robot machine cyber android bot tech futuristic",
  "🎃": "pumpkin jack-o-lantern halloween scary orange harvest carve",
  "😺": "cat happy grin meow feline",
  "😸": "cat smile smiling eyes happy meow feline",
  "😹": "cat tears of joy laugh meow feline",
  "😻": "cat heart eyes love meow feline catlove",
  "😼": "cat smirk sly feline meow cheeky",
  "😽": "cat kiss blow meow feline",
  "🙀": "cat shocked scream feline meow afraid scardy",
  "😿": "cat crying tear sad meow weep feline",
  "😾": "cat angry pouting mad meow rawr feline",

  // --- Hands & Body Parts ---
  "👋": "wave hello goodbye hand greeting hi bye",
  "🤚": "raised back of hand stop voting high five",
  "🖐️": "splayed fingers hand open five fingers highfive",
  "✋": "raised hand stop halt high five up",
  "🖖": "vulcan salute spock star trek alien geek space",
  "👌": "ok hand good positive perfect sign ok",
  "🤌": "pinched fingers Italian gesture perfect correct nice dainty",
  "🤏": "pinching hand tiny small little bit snippet",
  "✌️": "peace sign victory hand scissor layout",
  "🤞": "fingers crossed luck hope wish secure integrity",
  "🫰": "heart hand Kpop love fingers cute affection snapping",
  "🤟": "love you hand sign rock on metal heavy rock",
  "🤘": "rock on sign of horns devil metal heavy rock concert",
  "🤙": "call me hand phone surfer hang loose wave shake",
  "👈": "pointing left direction indicator back",
  "👉": "pointing right direction indicator forward next",
  "👆": "pointing up hand direction ceiling higher top",
  "🖕": "middle finger rude gesture bird flip",
  "👇": "pointing down hand direction bottom floor below",
  "☝️": "index pointing up note warning hold on first number one",
  "👍": "thumbs up like good yes positive agree confirm correct premium",
  "👎": "thumbs down dislike bad no negative disagree reject",
  "✊": "fist raise power strength strike resistance solid",
  "👊": "oncoming fist punch blow power hits fight",
  "🤛": "leftwards fist punch highfive side strike",
  "🤜": "rightwards fist punch highfive side strike",
  "👏": "clapping hands applause clap praise excellent well done",
  "🙌": "raising hands celebrate praise high five party hooray",
  "👐": "open hands together hug friendly offer giving receipt",
  "🤲": "palms up together request praying book giving charity",
  "🤝": "handshake agreement deal partner business teamwork together synergy",
  "🙏": "folded hands pray thank you please gratitude hope respect bow",
  "✍️": "writing hand pen pencil notes update edit write",
  "💅": "nail polish cosmetics beauty salon style custom classy fancy",
  "Selfie": "selfie photo mobile camera arm picture face",
  "📸": "camera flash photograph picture snapshot memory media",
  "🤳": "selfie mobile camera photo arm picture face portrait",
  "💪": "flexed biceps muscle power strength fitness sports gym healthy hard",
  "🦾": "robotic arm prosthetic power bionic machine tech strong",
  "🦿": "robotic leg bionic cyber prosthesis foot tech leg running",
  "🦵": "leg knee thigh limb sport foot run kicking",
  "🦶": "foot sole toes walking stand step sensory",
  "👂": "ear hear sound listen acoustic music noise receptor",
  "🦻": "ear with hearing aid accessory medical help assist listen",
  "👃": "nose smell scent air inhale breathe breathing snuff",
  "🧠": "brain mind think smart intelligence ideas mental thoughts",
  "🫀": "anatomical heart core cardio vascular medical life red",
  "🫁": "lungs breathing respirate pulmonary health medical chest air",
  "🦷": "tooth dental clean dentist decay bite teeth white",
  "🦴": "bone skeleton dog food treat calcium hard frame",
  "👀": "eyes looking viewing observing inspection search alert watch",
  "👁️": "eye vision look watch view observer optic single",
  "👅": "tongue lick appetite taste flavor language talk",
  "👄": "mouth lips speak talk gossip whisper red kiss",
  "💋": "kiss mark lipstick makeup romance passion sweet love",
  "🩸": "blood drop medicine donation red liquid bleed injured vampire",

  // --- Hearts & Love ---
  "❤️": "red heart love passion classic heart romance",
  "🧡": "orange heart love friendship warm bright",
  "💛": "yellow heart love friendship sunshine golden cheer",
  "💚": "green heart love envy jealousy eco environment organic Nature",
  "💙": "blue heart love trust support loyalty sky deep",
  "💜": "purple heart love rich elegant royalty purple creative",
  "🖤": "black heart love gothic dark heavy emo sorrow",
  "🤍": "white heart love pure clean crystal peace light",
  "🤎": "brown heart love warm chocolate coffee wood comfort",
  "💔": "broken heart sad breakup sorrow divorce hurt unlove",
  "❤️‍🔥": "heart on fire burning passion love extreme hot desire",
  "❤️‍🩹": "mending heart healing recovery better bandage fix love",
  "❣️": "heart exclamation punctuation alert mark love priority",
  "💕": "two hearts pink romance cute hearts fly float sweet",
  "💞": "revolving hearts pink love romance circle synergy spin",
  "💓": "beating heart pink pulse rate live heart vibration warm",
  "💗": "growing heart pink love growing expanding sweet",
  "💖": "sparkling heart pink stars magic premium love shiny glitter",
  "💘": "heart with arrow cupid target strike hit romantic love valentine",
  "💝": "heart with ribbon gift box surprise love packaging sweet valentine",

  // --- Animals & Creatures ---
  "🦁": "lion animal cat predator king wild safari roar gold green",
  "🐺": "wolf dog predator animal wild coyote grey howling",
  "🦊": "fox animal wild red ginger intelligent trickster",
  "🦝": "raccoon trashpanda masked animal wild raccoon grey forest",
  "🐱": "cat face pet meow feline kitten kitty whiskers",
  "🐈": "cat whole body pet feline standing purr meow walking",
  "🐈‍⬛": "black cat pet halloween luck mystery feline shadow",
  "🐶": "dog face pet puppy bark canine woof friendly paws",
  "🐕": "dog standing puppy pet canine loyal guardian walking",
  "🐩": "poodle dog custom breed pet fluffy classic",
  "🦮": "guide dog assistant helper blind patient service walking canine",
  "🐕‍🦺": "service dog worker harness helper backup guard dog canine",
  "🐯": "tiger face wild cat predator stripes orange hunter jungle rawr",
  "🐅": "tiger standing wild cat stripes predator jungle asian",
  "🐆": "leopard wild cat speed fast spots safari predator panther",
  "🐴": "horse face equine farm ride racing stallion",
  "🫏": "donkey burro farm animal mule gray obstinate stubborn",
  "🐎": "horse standing race running ride equestrian speed",
  "🦄": "unicorn horse magical fairytale fantasy horn star pink white rainbow",
  "🫎": "moose deer forest antlers wild wildlife giant wood",
  "🦌": "deer buck forest stag antlers fawn wildlife bambi",
  "🦬": "bison buffalo wild prairie herd heavy wilderness",
  "🐮": "cow face dairy farm milk beef pasture cute",
  "🦛": "hippo hippopotamus safari heavy river water wild",
  "🐏": "ram sheep horns farm wool male zodiac sign",
  "🐑": "ewe sheep farm lamb wool fluffy white cloud fleece",
  "🐐": "goat farm animal billy pasture horns capricorn climb",
  "🐪": "camel desert dromedary hump sand middle east travel dry",
  "🐫": "camel bactrian desert double hump load caravan travel",
  "🦙": "llama alpaca zoo farm animal wool spit Peru",
  "🦒": "giraffe tall neck spots safari savanna green yellow tall",
  "🐘": "elephant safari trunk tusk mammal water jungle large wild gray",
  "🦣": "mammoth iceage ancient giant tusk fur prehistoric extinct",
  "🦏": "rhino rhinoceros tusk horn heavy wild safari armor",
  "🐭": "mouse face rodent pet pest cheese squeak",
  "🐁": "mouse standing rodent white lab pet pest",
  "🐀": "rat rodent dark pest sewer long tail mouse",
  "🐹": "hamster cheeks cute pet rodent wheel gerbil fluff",
  "🐰": "bunny rabbit ears carrot easter pet hopping fluffy",
  "🐇": "rabbit standing bunny carrot pet easter jumping",
  "🐿️": "chipmunk squirrel forest nut acorn rodent chip n dale chew",
  "🦫": "beaver dam river forest wood builder teeth rodent",
  "🦔": "hedgehog prickles needles cute small woodland spiny sonic",
  "🦇": "bat night fly vampire wings halloween gothic caves mammal",
  "🐻": "bear face teddy brown wilderness forest grizzly roar paws",
  "🐻‍❄️": "polar bear ice snow winter cold safe arctic wilderness",
  "🐨": "koala bear tree marsupial Australia cute eucalyptus zoo sloth",
  "🐼": "panda bear black white bamboo china asian cuddly cute",
  "🦥": "sloth slow crawl lazy tree sleepy brown fur rainforest",
  "🦦": "otter river water aquatic cute play swim whiskered ferret",
  "🦨": "skunk scent stink spray smelly black white stripe forest",
  "🦡": "badger wild forest claws fierce underground burrow",
  "🐸": "frog amphibian toad green hop pond croak splash",
  "🐊": "crocodile alligator swamp reptile predator snapping teeth green",
  "🐢": "turtle tortoise reptile shell slow beach ocean green crawl",
  "🦎": "lizard reptile chameleon gecko dragon scales tails",
  "🐍": "snake serpent reptile scales crawl venom danger slither hiss",
  "🐲": "dragon face mythical fairytale green magic wings fire scifi asian",
  "🐉": "dragon whole body mythical green fire monster chinese zodiac serpent",
  "🦕": "sauropod dinosaur diplodocus herbivore giant neck fossil jurassic jurasic",
  "🦖": "t-rex dinosaur tyrannosaurus rex predator rawr jurassic extinct scales",
  "🐳": "spouting whale blowhole ocean sea fish water aquatic marine giant",
  "🐋": "whale ocean blue sea giant humpback marine mammal",
  "🐬": "dolphin ocean sea smart mammal swim jumping play marine",
  "🦭": "seal sea lion marine aquatic ocean polar beach cute sealion",
  "🐟": "fish ocean sea marine aquatic food pet scales swim",
  "🐠": "tropical fish coral reef colorful pet neon exotic ocean",
  "🐡": "blowfish puffer fish spiky balloon spike defense seafood balloonfish",
  "🦈": "shark predator tooth jaw bite danger terror ocean sea predator seafood",
  "🐙": "octopus marine sea ocean ink intelligence tentacles aquatic alien tentacles tentacle",
  "🦑": "squid marine sea seafood ocean ink aquatic calamari",
  "🪼": "jellyfish sting transparent sea ocean water drift bell bloom",
  "🦐": "shrimp lobster seafood ocean marine prawn",
  "🦞": "lobster claws sea seafood red marine shell",
  "🦀": "crab claws beach ocean sea shell zodiac sign cancer seafood",

  // --- Bugs & Insects ---
  "🐝": "bee honeybee flower honey sting insect wings buzz",
  "🪱": "worm soil earthworm crawl pink worm ground dirt",
  "🐛": "caterpillar bug green insect butterfly pupa cocoon",
  "🦋": "butterfly wings color fly insect flowers cocoon wings",
  "🐌": "snail shell slow crawl trail slimy garden",
  "🐞": "ladybug ladybeetle beetle red spots insect garden black dots",
  "Ant": "ant insect colony workers bug small sugar ground",
  "🐜": "ant insect colony worker bug small black soil crawling",
  "🪰": "fly buzzing insect wings bug dirt garbage nuisance",
  "🪲": "beetle insect bug shell horn nature collector",
  "🪳": "cockroach roach pest crawler dirty bug insect house nuisance",
  "🦹": "villain supervillain cape evil scifi character mask rogue",
  "🦟": "mosquito bug insect sting blood flu bite itch wings disease malaria",
  "🦗": "cricket grasshopper insect green hop sound chirp",
  "🕷️": "spider eight legs web cobweb bug arachnid insect scary halloween crawl",
  "🕸️": "spiderweb web cobweb net trap architecture halloween spider",
  "Scorpion": "scorpion desert sand poison tail sting predator zodiac scorpio claws",
  "🦂": "scorpion desert venom tail sting poison claws zodiac scorpio arachnid scary",

  // --- Nature, Plants & Flowers ---
  "💐": "bouquet flowers florist rose stems wedding ribbon gift beauty",
  "🌸": "cherry blossom sakura flower pink spring Japanese bloom garden",
  "💮": "white flower rosette stamp validation Japanese premium good paper",
  "🪻": "hyacinth flower lavender purple blue spring garden bunch bouquet",
  "🌹": "rose flower red love romantic romance thorns valentine beauty",
  "🥀": "wilted flower fading rose dead dropped sad unhappy end blossom drying",
  "🌺": "hibiscus flower tropical red beach aloha hawaii exotic warm summer",
  "🌻": "sunflower tall yellow seeds sun bright summer positive seed",
  "🌼": "blossom yellow flower daisy spring wild garden bloom chamomile",
  "🌷": "tulip flower pink red spring dutch garden bouquet bloom",
  "🌱": "seedling plant sprout growth green nature start business new beginnings",
  "🪴": "potted plant indoor green leaves home decoration oxygen eco garden",
  "🌲": "evergreen pine tree needle forest conifers wilderness winter wood Nature",
  "🌳": "deciduous tree leaves oak forest wilderness trunk green park Nature",
  "🌴": "palm tree beach tropical warm vacation island coco sand Summer",
  "🌵": "cactus desert prickles sand spikes green warm dry water western",
  "🌾": "sheaf of rice wheat grain cereal straw harvest bread agriculture",
  "🌿": "herb leaf organic green pharmacy medicine culinary seasoning Nature",
  "☘️": "shamrock clover three leaves Irish luck green Patrick saint",
  "🍀": "four leaf clover shamrock lucky charm green Patrick luck supreme dream",
  "🍁": "maple leaf red autumn fall canada syrup foliage seasons change",
  "🍂": "fallen leaves autumn fall foliage orange brown seasons Nature",
  "🍃": "leaf fluttering in wind breeze fresh clean green blow air tea Nature",
  "🍄": "mushroom toadstool fungus forest red spot organic magic nature spore",
  "🌰": "chestnut acorn nut harvest snack brown squirrel food",
  "🪨": "rock stone pebble hard solid mineral fossil mountain slate",
  "🪵": "wood log timber campfire forest build lumber chopped brown tree",
  "🌊": "water wave ocean sea surf tsunami dynamic blue motion splash energy",
  "🌬️": "wind blowing face breeze weather cold storm autumn blow wind-face",
  "🌀": "typhoon hurricane cyclone portal spiral blue spin vortex rotate",
  "⭐": "star yellow sky glowing rank premium favorite rating medal spark",
  "🌟": "glowing star yellow bright sparkle outstanding brand magic spark",
  "✨": "sparkles stars shiny gold fairy magic clean premium new neon glitter",
  "⚡": "high voltage lightning bolt thunder electricity battery power energy flash fast strike storm",
  "🔥": "fire flame hot burning heat campfire spicy popular fever priority wildfire",
  "🌈": "rainbow colors weather sky sky-colors after rain pride colorful lgbt",
  "☀️": "sun sunlight warm weather bright day Summer solar heat star",
  "🌤️": "sun behind small cloud sky weather daylight pleasant day",
  "⛅": "sun behind cloud sky weather moderate warm seasons",
  "🌥️": "sun behind large cloud sky weather cloudy gray day overcast",
  "☁️": "cloud sky weather white fluffy fog shade rain",
  "🌦️": "sun behind rain cloud shower weather sky rainbow wet",
  "🌧️": "rain cloud weather wet storm storm-cloud damp weather droplets",
  "🌨️": "snow cloud winter cold weather ice frozen snowflake skiing blizzard",
  "🌩️": "lightning cloud thunder storm flash voltage electric power dark sky weather",
  "🌪️": "tornado twister storm wind weather hazard damage funnel wild hurricane",
  "🌫️": "fog weather mist steam smoke smog blind visible condensation gray",
  "❄️": "snowflake ice crystal winter cold frozen glacier white ski chill weather",
  "⛄": "snowman snow winter cold frozen ice snowman-face holiday christmas",
  "☄️": "comet asteroid space fire flame star rock fall universe",
  "🌌": "milky way sky stars galaxy space universe deep night cosmic cosmos",
  "🌍": "europe africa globe earth planet world atlas continent map space geography",
  "🌎": "americas globe earth planet world land ocean continent space geography map",
  "🌏": "asia australia globe earth planet world ocean continent space map geography",
  "🪐": "ringed planet saturn orbit space science scifi cosmos universe gravity",
  "🌙": "crescent moon night sleep bedtime dream evening dark waxing waning",
  "🌘": "waning crescent moon dark night sky celestial cycles",
  "🌗": "last quarter moon half moon night sky space cycle",
  "🌖": "waning gibbous moon space sky celestial starry",
  "🌕": "full moon lunar glowing round sphere night werewolf tides magic",

  // --- Food & Drink ---
  "🍇": "grapes fruit wine vineyard food sweet dessert purple clusters",
  "🍈": "melon fruit sweet honeydew cantaloupe slice green healthy",
  "🍉": "watermelon slice red seeds sweet summer pool giant fruit beach water",
  "🍊": "tangerine orange citrus fruit sweet juice acid zest immune",
  "🍋": "lemon citrus fruit sour acid yellow juice lemonade vitamin peel",
  "🍌": "banana yellow fruit potassium peel monkeys tropical sweet energy",
  "🍍": "pineapple pine tropical fruit spikes crown sweet pina colada yellow and orange",
  "🥭": "mango tropical fruit sweet peach juicy soft orange yellow",
  "🍎": "red apple fruit teachers healthy doctor snack juice green stem",
  "🍏": "green apple fruit crisp tart healthy organic smith",
  "🍐": "pear fruit green sweet soft shape healthy pear-shaped",
  "🍑": "peach fruit soft orange pink sweet dessert cozy",
  "🍒": "cherries red fruit double pair stem sweet cherry-pie juice berry",
  "🍓": "strawberry red seeds sweet berry fruit cream summer dessert jam",
  "🫐": "blueberries berry fruit blue antioxidant healthy sweet crumble yogurt",
  "🥝": "kiwi fruit slice green brown fuzzy exotic vitamin",
  "🍅": "tomato red salad ketchup soup vegetable garden sauce red-vegetable",
  "🫒": "olive green oil greek pizza branch peace organic jar",
  "🥥": "coconut tropical island shell water milk beach vacation coir",
  "🥑": "avocado green toast fat guacamole seed salad healthy cream",
  "🍆": "eggplant aubergine vegetable purple long plant cooking",
  "🥔": "potato starch vegetable baked fries potato chips farm brown",
  "🥕": "carrot vegetable orange roots bunny rabbit eyes eyes-healthy farm",
  "🌽": "corn ear cob maize popped sweet farm yellow kernels popcorn",
  "🌶️": "hot pepper chili red spicy hot food Mexican heat cooking condiment",
  "🫑": "bell pepper green yellow red sweet vegetable salad cook crunch Capsicum",
  "🧅": "onion vegetable tears flavor cooking kitchen bulb layers garlic",
  "🧄": "garlic bulb cloves smell vampire medicine cooking seasoning kitchen",
  "🫘": "beans legumes protein healthy chili soup seed pod refried Mexican",
  "🥬": "leafy green lettuce cabbage salad organic Nature raw detox spinach",
  "🥦": "broccoli green vegetable trees health diet steam cook salad florets",
  "🥜": "peanuts peanut-butter nuts shell legume allergy healthy snack chew",
  "🥐": "croissant bakery bread pastry French breakfast butter flake dough baking",
  "Bread": "bread loaf toast baking bakery sandwich carbs slice wheat",
  "🍞": "bread loaf slice toast bakery wheat white flour toast",
  "🥖": "baguette bread French long loaf baking bakery crusty classic",
  "🫓": "flatbread naan pita tortilla bread taco wraps baking kitchen",
  "🥨": "pretzel knot salty bakery loop snack beer German Octoberfest baker",
  "Bagel": "bagel circular bread toast hole bakery cream-cheese breakfast",
  "🥯": "bagel round bread doughnut loop toast bakery cream cheese breakfast",
  "🥞": "pancakes stack butter syrup breakfast hotcake sweet bakery brunch maple",
  "Waffle": "waffle grid syrup breakfast sweet butter grid-batter waffle-iron brunch",
  "🧇": "waffle grid syrup breakfast sweet butter brunch grid-batter",
  "Cheese": "cheese swiss yellow block wedges hole pizza mouse dairy",
  "🧀": "cheese wedge dairy swiss yellow block hole cows goat mouse milk",
  "🍖": "meat on bone cartoon bbq animal food dog chew ribs loin grill",
  "🍗": "poultry leg chicken turkey fried bbq drumdrum drumstick wings birds meat",
  "🥩": "steak cut of meat raw beef grill barbecue protein dinner",
  "Bacon": "bacon pork strip greasy crispy fried slice breakfast eggs smoke",
  "🥓": "bacon strips pork breakfast crispy greasy fried smoke meat",
  "🍔": "hamburger burger fastfood beef patty cheese lettuce buns grilled takeout",
  "🍟": "french fries potato chips fastfood salty snack potato ketchup takeout",
  "🍕": "pizza slice cheese pepperoni Italian crust baking tomato fastfood takeout",
  "🌭": "hot dog fastfood sausage buns mustard ketchup barbeque yankee snack",
  "🥪": "sandwich lunch bread slice cheese lettuce ham turkey snack picnic",
  "🌮": "taco Mexican tortilla beef cheese lettuce spicy fastfood salsa wrap",
  "Burrito": "burrito wrap Mexican tortilla rice beans meat cheese fastfood takeout",
  "🌯": "burrito Mexican wrap tortilla rice beans meat cheese fastfood",
  "🫔": "tamale corn husk Mexican food masa dough meat cooking festival",
  "Salad": "salad bowl green lettuce healthy raw vegetable vegan organic diet",
  "🥗": "green salad bowl healthy raw vegetables lettuce vegan diet cucumber carrot",
  "🍿": "popcorn movie theater popcorn-box buttered snack popped corn grain",
  "Butter": "butter block yellow dairy toast spread bake cooking fat yellow-spread",
  "🧈": "butter block dairy spread toast baking fat cooking yellow cow yellow block",
  "🍘": "rice cracker senbei Japanese oriental snack crispy soy round seaweed",
  "🍙": "rice ball onigiri seaweed Japanese snack triangle meal lunchbox sushi",
  "🍚": "cooked rice bowl white steam grain grain-bowl lunch dinner asian",
  "🍛": "curry and rice hot spicy indian asian stew sauce carrots beef",
  "🍜": "ramen steaming bowl noodles soup chopsticks Japanese asian fastfood pasta",
  "🍝": "spaghetti pasta noodles tomato sauce meatballs fork swirl Italian dinner",
  "🍠": "roasted sweet potato yam orange purple warm winter Japanese snack",
  "🍢": "oden skewer Japanese seafood fishcakes broth hot winter streetfood",
  "🍣": "sushi salmon roll rice seaweed raw fish wasabi chopsticks soy Japanese asian",
  "🍤": "fried shrimp tempura seafood crunchy crustacean chopsticks Japanese snack",
  "🍥": "fish cake pink swirl naruto ramen topping seafood slice Japanese",
  "🥮": "mooncake mid-autumn festival Chinese pastry sweet sweet-bean lotus yolk bakery",
  "🍡": "dango sweet skewers rice dumplings green pink white japanese sweet asian",
  "🥟": "dumpling gyoza potsticker wrap meat vegetable asian chopsticks steamed dimsum",
  "🥠": "fortune cookie message advice crispy sweet chinese takeaway baking dessert",
  "🥡": "takeout box noodles box delivery cardboard fold chinese fastfood takeout-box",
  "🍦": "soft serve icecream cone vanilla chocolate twist dairy sweet cold summer",
  "🍧": "shaved ice syrup flavor glass cold summer beach japanese ice-shave",
  "🍨": "ice cream scoop bowl dessert sweet dairy cold vanilla strawberry cherry",
  "🍩": "donut doughnut ring sweet glaze pastry sprinkles custom bakery sugar frosting",
  "🍪": "cookie chocolate chip cookies baking biscuit dessert sweet baker bakery snack crumbs",
  "🧁": "cupcake cake baking icing cherry sprinkles sweet dessert birthday custom",
  "🥧": "pie fruit bake pastry crust apple baking dessert thanksgiving slice",
  "🍫": "chocolate bar brown sweet candy cocoa sugar snack treat dessert block",
  "🍬": "candy wrap sweet sugar colorful caramel snack lollipop",
  "🍭": "lollipop candy swirly sweet sugar colorful child lollipop stick",
  "🍮": "custard flan pudding caramel cream sweet yellow dessert gelatin jelly",
  "🍯": "honey pot honeypot bee bear sweet jar yellow gold breakfast bee-hive",
  "Milk": "milk glass drink calcium dairy cow white liquid glass of milk bottle",
  "🥛": "glass of milk dairy calf cow calcium white breakfast drink bottle",
  "☕": "hot beverage coffee tea cup steam mug cafe morning espresso espresso-cup caffe caffeine",
  "🫖": "teapot ceramic vessel tea infusion drink hot ceremony pot porcelain",
  "🍵": "teacup helper green matcha tea cup leaf ceremony warm asian drink no-handle",
  "Mate": "mate drink gourd straw green herbs south america traditional caffeine hot",
  "🧉": "mate cup gourd metal straw green herbs argentina uruguay caffeine hot drink",
  "🥤": "cup with straw soda softdrink cola cup plastic cinema fastfood drink pop",
  "🧋": "bubble tea boba milk tea tapioca pearls straw sweet asian drinks",
  "Sake": "sake cup bottle rice wine Japanese traditional alcohol toast decanter bar",
  "🍶": "sake bottle cup decanter drink rice wine japanese bar pub alcoholic toast",
  "🍺": "beer mug foam golden stout ale alcohol pub bar toast drinks lager",
  "🍻": "clinking beer mugs toast celebration pub bar party cheer lagers tavern",
  "🥂": "clinking glasses champagne sparkling wine celebration wedding party newyear toast",
  "🍷": "wine glass red grapes alcohol pub fine dining bar cabernet bottle toast",
  "🥃": "tumbler glass whiskey bourbon scotch rum ice cocktail bar pub drink neat",
  "🍸": "cocktail glass martini olive classy fancy bar lounge alcohol pub green-olive drink",
  "🍹": "tropical drink cocktail tiki orange slice straw summer pool beach bar alcohol sun",
  "🍾": "bottle with popping cork champagne sparkling celebration wedding newyear festive party sparkling-wine",
  "🧊": "ice cube water frozen solid transparent melt square blocks cold chill freezing",

  // --- Activity, Sports & Games ---
  "⚽": "soccer ball football sport stadium athlete match goal kickoff kick green",
  "🏀": "basketball ball orange sport court hoop dunk rebound athlete orange-ball",
  "🏈": "american football oval leather pigskin touchdown helmet NFL sport superbowl yards",
  "⚾": "baseball ball sport glove field homerun seams white-ball bat pitcher pitch",
  "🥎": "softball green yellow ball bat sport pitch pitcher fastpitch female",
  "🎾": "tennis ball racket court volley green yellow match sport set deuce play",
  "🏐": "volleyball ball sand beach court sport spike block set serve digital",
  "🏉": "rugby union ball oval match tackle sport kick league worldcup try",
  "🥏": "flying disc frisbee ultimate throw beach park disk sport layout",
  "🎱": "pool 8 ball billards game table cue black sphere pocket rack snooker",
  "🪀": "yo yo string toy spin loop trick child kids retro fun up-and-down",
  "🏓": "ping pong paddle ball table-tennis set match volley paddle court",
  "🏸": "badminton racket shuttlecock birdy net court volley swing smash sport",
  "🏒": "ice hockey stick puck ice arena helmet winter sport league goals penalty skates",
  "🏑": "field hockey stick ball grass turf sport run team pass goalie",
  "🥍": "lacrosse stick pocket mesh gloves helmet balls turf athletic run sport",
  "🏏": "cricket bat ball wickets stumps pitch match run batsman bowler wickets bowler sport",
  "🪃": "boomerang wood throw return wind fly hunter air australia weapon dynamic",
  "🥅": "goal net soccer hockey lacrosse target score post arena frame",
  "⛳": "golf flag hole green putter irons fairway links bunker cart sport drive",
  "🏹": "bow and arrow target hit archery shooting bullseye weapon hunting arrow sport",
  "🎣": "fishing pole rod fish hook catch water lake bait catch-fish reel angle",
  "🤿": "diving mask snorkel glass water sea ocean swim beach underwater dive deep",
  "Boxing": "boxing glove red punch fight match ring champion strike power fit knock-out",
  "🥊": "boxing glove red punch power fight combat match gym sports ring fist knock-out",
  "🥋": "martial arts uniform judo karate taekwondo black belt belt combat dojo asian",
  "Running Shirt": "running shirt jersey singlet track athletic marathon gym sport racing custom",
  "🎽": "running shirt singlet ribbon sash marathon track athlete race clothing gym",
  "Skateboard": "skateboard deck wheel roll trucks flip board park street kickflip skate board",
  "🛹": "skateboard deck roll wheels trucks halfpipe skate board street ride",
  "🛼": "roller skate skates quad custom wheels retro rink disco speed rolling",
  "🛷": "sled toboggan snow winter slide speed sports sleigh run",
  "⛸️": "ice skate winter cold arena figure skating blade speed ice gliding",
  "🥌": "curling stone red yellow ice glide sweep broom strategy tournament rocks",
  "🎿": "skis ski poles snow winter mountain slope cold fast descending downhill",
  "⛷️": "skier snow winter mountain slope cold sport athlete descending sliding ski",
  "🏂": "snowboarder snow winter mountain slope cold halfpipe fast slope rider boarder",
  "🏋️": "weightlifter bar barbell bodybuilder fitness strength sport dumbbells crossfit",
  "🤺": "fencer sword fight épée foil sabre combat mask helmet white gear lunging duel",
  "🤼": "wrestlers wrestling grab combat canvas match ring fight sports grappling ground-combat",
  "🤸": "gymnast layout acrobatics gymnastics cartwheel flip athletic flexibility balance floor sport",
  "⛹️": "basketball player bounce dribble athlete court ball hoop jersey sport",
  "🤾": "handball player team court throw pass jumping scoring goals sport jersey",
  "🧗": "climber scale mountain rock wall ropes harness extreme sport elevation altitude hiking climbing",
  "🚴": "cyclist ride bike bicycle custom speed pedal path tour road sports racer racers",
  "🚵": "mountain biker dirt trails bike bicycle suspension helmet hills trees outdoor cycle mtb",
  "🏆": "trophy prize winner gold champion placement rank award honor premium supreme top",
  "🥇": "gold medal first place winner premium rank champion badge medal-1st honor top",
  "🥈": "silver medal second place rank runnerup winner medal-2nd silver-prize",
  "🥉": "bronze medal third place rank medal-3rd bronze-prize placement award",
  "🏅": "sports medal ribbon reward placement event contest games run racing award honor",
  "🎖️": "military medal ribbon star honor duty military bravery hero award badge decoration",
  "🏵️": "rosette ribbon decoration prize flower placement award victory design",
  "🎫": "ticket admission event entry show movie theatre sport concert pass voucher",
  "🎟️": "admission tickets pair entry event show theater concert sport movie coupon",
  "🎭": "performing arts drama masks comedy tragedy theatre actor playing custom acting stage",
  "🎨": "artist palette watercolor paint paintbrush brush designer creative color art draw digital illustration logo",
  "🎬": "clapperboard movie cinema slate director filming action roll hollywood video studio editor",
  "🎤": "microphone stand singing vocals audio sound record mic podcast host talk live-music concert",
  "🎧": "headphone head headset audio listener audio music DJ sounds songs podcast digital",
  "🎼": "musical score notes sheet-music classical song melody key staff clef singing",
  "🎹": "musical keyboard piano keys synthesizer tune music melody notes chords synth-keys chords",
  "🥁": "drum sticks snare kick jazz percussion rhythm beat play instrument sound",
  "🎷": "saxophone brass jazz blues keys band music tune melody wind-instrument blowing horn",
  "🎺": "trumpet brass orchestra fanfare blowing horn band valve jazz parade fanfare-horn",
  "🎸": "guitar acoustic electric chords strings wood rock pop country music layout",
  "🪕": "banjo country bluegrass string instrument wood chords folk music banjo-strings",
  "Violin": "violin fiddle classical orchestra string strings bow instrument layout cello",
  "🎻": "violin classical bow strings orchestra instrument wood music melody",
  "🎲": "game die dice boardgame random luck roll gaming Vegas casino croupier",
  "♟️": "chess pawn piece boardgame strategy thinking defense game security",
  "🎯": "bullseye direct hit target arrow dart board shooting win accuracy goals center target-board precision",
  "Bowling": "bowling pins ball strike lane spare alley game roll pins sports recreation",
  "🎳": "bowling pins ball strike spare alley game lane roll recreation sports tenpin",
  "🎮": "video game controller console gamepad buttons playstation xbox switch gaming gamer stream cyber",
  "🎰": "slot machine casino Vegas gambling luck coins pull jackpots money payout spin bar",
  "🧩": "jigsaw puzzle block pieces connect missing-piece fit strategy brain layout analytical",

  // --- Objects, Tools & Tech ---
  "💎": "gem stone diamond crystal jewel precious rich jewelry premium spark blue shiny clean sparkle",
  "💡": "light bulb dynamic idea inspiration bright energy source glass glow insight innovation solution creator",
  "🚀": "rocket spaceship outer space launch fast dynamic speed booster explorer astronauts scifi future skyways high",
  "💻": "laptop computer monitor screen keyboard trackpad desk workplace code developer programming technology laptop",
  "📱": "mobile phone smartphone screen wireless network tech communication call messenger devices screen",
  "⌚": "watch timepiece wrist clock clockwork scheduling countdown check hour custom",
  "⌨️": "keyboard typing tech typing-board keys write edit layout coding computer accessory",
  "🖱️": "computer mouse clicking pointer scroll tech cursor computer accessory scroll-wheel",
  "🕹️": "joystick retro game arcade flight controller retro grip stick gaming computer accessory",
  "🔌": "electric plug cable wires electricity current outlet adapter connector power charging",
  "🔋": "battery green cells energy storage power accumulator charge charging level cell",
  "💾": "floppy disk save files data storage technology custom drive 3.5 backup retro",
  "💿": "optical disk CD DVD blu-ray disc drive spin circle silver laser memory storage records",
  "📷": "camera photograph classic lens snapshot captures photo media image",
  "📹": "video camera camcorder recording filming custom video-camera storage tape movie production",
  "🎥": "movie camera cinema filmmaking projector hollywood retro video tape stream recording studio film-reel",
  "📺": "television retro TV screens broadcasting tube box oldscreen cathode analog video display screen-box",
  "📻": "radio retro tune receiver sound audio broadcast frequency waves signals dynamic",
  "🎙️": "studio microphone stand audio radio sound recording mic podcast host narrator broadcasting",
  "⏱️": "stopwatch timing millisecond countdown scheduling watch sport tracker lap",
  "⏰": "alarm clock bells bedtime morning snooze awaken timeline dynamic hours clock",
  "🧲": "magnet red blue polarity field metallic attraction pull physics force magnetics",
  "🔨": "hammer tool nail building construction woodwork hardware mallet build fix repair",
  "🪓": "axe hatchet wood chop forest build wooden tool blade hardware lumberjack survival",
  "⛏️": "pickaxe pick mine gold ore rocks minerals mountain digging heavy hard tool steel",
  "⚒️": "hammer and pick repair tool construction work mechanic mining hard workers craft",
  "🛠️": "hammer and wrench mechanic repair tool hardware fixing construction garage key bolt settings",
  "🗡️": "dagger knife blade weapon sharp steel cuts custom medieval rogue",
  "⚔️": "crossed swords combat defense weapon knights army war steel blades",
  "🛡️": "shield defense guards protection armor safe emblem security fortress castle integrity knights",
  "🔧": "wrench tool spanner bolt hex nut hardware repairs auto service workshop mechanic plummer",
  "🪛": "screwdriver tool screw drivers tip handle hardware mechanic build workshop assembling slots",
  "⚙️": "gear cog wheels rotation setup mechanism configuration machine engine custom system settings core",
  "🧱": "bricks wall building red blocks clay construction mortar modular masonry stable masonry-wall",
  "🔮": "crystal ball crystalball fortune magic future oracle celestial predict orb glowing mystical wizard",
  "🧬": "dna double helix biology gene science doctor code life evolution medical spiral laboratory research",
  "🧪": "test tube glass medical green liquid chemistry science biology laboratory experiments pharmaceutical",
  "🧫": "petri dish bacteria growth biology medical laboratory cell organism growth-medium",
  "🔬": "microscope lens zoom scientist laboratory medical biology slides research cells study inspect detail",
  "🔭": "telescope stars sky search galaxy moon outer space observatory celestial lens look far-reaching",
  "📡": "satellite antenna dish signals communications network internet technology broadcaster celestial sky space reception",
  "🩺": "stethoscope doctor nurse hospital medical diagnostics heartbeat inspect healthcare breath clinical",
  "💉": "syringe needle medical doctor nurse shot injection vaccine clinical fluid blood health hospital",
  "💊": "pill capsule medicine doctor prescription disease health painkiller drugs pharmacy tablet chemical",
  "🩹": "adhesive bandage patch strip hurt wound skin healing recovery medical hospital health guard",
  "🧹": "broom sweeps dust cleaning cleaner brush floor domestic service housekeeping",
  "🧺": "basket woven container laundry wash hold organizer household picnic hamper bread-basket",
  "🧼": "soap bubble lather wash clean hygiene bath shower bar domestic liquid-soap",
  "🧽": "sponge yellow wash bubbles absorb cleans cleaning kitchen bath car accessory scrubbing",
  "🪣": "bucket pail water household metal plastic clean laundry handle hold red-bucket fluid",
  "🔑": "key open lock padlock access metal gold solution secret password secure login accessory clue",
  "🗝️": "old key vintage antique access secret door lock secure mystery castle retro clues",
  "🔒": "locked padlock security closed secure guard protect privacy encrypt safety keyhole key",
  "🔓": "unlocked open padlock security status release decrypt accessibility clearance access safe keyhole",
  "🔐": "locked key padlock secure login digital certification privacy password protection encrypt verification keys",
  "🔔": "bell ringer notification alarm yellow alerts bronze sounds golden reminder alert-bell ringtones ringer",
  "🔕": "bell with slash mute silent quiet notifications silent-mode off pause sleep do-not-disturb",
  "📣": "megaphone announcer speaker broadcast news alert orange audio sounds attention volume micro",
  "📢": "loudspeaker announcer public address system sound broadcaster volume notifications stream broadcast-speaker",
  "🔈": "speaker low sound level audio acoustic bar volume silent lower digital speaker-cone icon",
  "🔊": "speaker high volume audio sound speaker-cone output dynamic acoustics louder music play",
  "📯": "postal horn post carriage mail envelope signals posthorn yellow trump brass",
  "✉️": "envelope mail letter postage stamp messages inbox mailbox dynamic inbox-letter card envelope-front paper",
  "📦": "package cardboard box shipping packing store delivery postal logistics storage brown-box contents-box",
  "📁": "file folder document organization store yellow tabs paperwork yellow-folder system storage archive",
  "📂": "open file folder doc directory files archive system yellow tabs loading storage yellow-folder",
  "🗂️": "card index dividers documents notes system tracking registry database categorization workspace organizers",
  "📅": "calendar date day schedule year plans appointments sheets timeline desk records days month",
  "📆": "tear-off calendar date day schedule event time sheets year month deadline plans notepad",
  "🗒️": "spiral notepad notes pads lines sheets paper notebook sketching drawing planner custom drafting",
  "📈": "chart increasing stocks analytics statistics growth trending upward lines values success profits graph",
  "📉": "chart decreasing stocks analytics downward lines values drop decline loss graph tracking",
  "📊": "bar chart analytics metrics statistics segments comparison report data numbers graph",
  "📋": "clipboard form papers notes document checklists priorities audits reports exam paper surveys evaluation tasklist",
  "📌": "pushpin red pin note board alerts alert-pin locate points mark paper-holder nails maps",
  "📍": "round pushpin red pin boards markers destination location geo GPS address track pinpoint",
  "📎": "paperclip clip files paper fastener fasteners attachment accessory wire loops school workspace",
  "🖇️": "linked paperclips connect attachments binder documents pairs clips fastners metal joints synergy",
  "📐": "triangular ruler math triangle geometry school engineer architectures measures technical-drawing scale",
  "📏": "straight ruler measures centimeters scale inches straight-line school math tool architect sizing",
  "📔": "notebook cover design spiral bound gold leaf journal reading diary sketch book sketchpad",
  "📕": "closed book red reading stories knowledge learning library study cover design bookstack",
  "📗": "green book closed cover story reading catalog guidelines library study manuals bookstack",
  "📘": "blue book closed story catalog reading guide directories library university textbooks manual cover doc",
  "📙": "orange book closed manual catalog reading literature study libraries bookstack orange-cover",
  "📚": "books stack of books stack library research studying reads papers bookshelves education textbook reading-pile",
  "📖": "open book sheets content story reading learn textbook manuals pages guidelines bookmark",
  "🔖": "bookmark label ribbon tag reads marking books libraries placeholders",
  "🧷": "safety pin diaper safety-pin baby metal loop sewing needle latch pinholders fastner clips",
  "🔗": "link chain custom anchor connection ties urls hyper-link connection-chain pairing synergizes",
  "✏️": "pencil write drafting drawing custom eraser yellow-pencil graphite school sketch write-tool",
  "✒️": "black nib fountain-pen fountain signature write calligraphies nib penholder classic ink",
  "🖋️": "fountain pen signature writes writing-tool calligraphies ink ballpoint designer signatures",
  "🖊️": "ballpoint pen signature writing writes notes paper-holder draft records ball-pen ink",
  "🖌️": "paintbrush brush creative art designs paint stroke color sketch layout color-palette oil-paint",
  "🖍️": "crayon red child draw sketch color colorful kids school wax-coloring art-tool chalk",
  "📝": "memo notes pencil writing write reports audits lists papers reviews logs record task-form page",
  "💼": "briefcase leather suit bag portfolio business workplace professional travel documents folder case",
  "🎒": "backpack schoolbag satchel kids camping traveling canvas bag hiking student zipper straps",
  "🔪": "knife kitchen chef blade cutlery tool sharp cut slice steak weapon dagger",
  "🧢": "cap blue baseball hat headwear accessory clothing sport rawr",
  "🎩": "hat top hat gear head classy formal top-hat magician retro dress clothing accessory",
  "👑": "crown gold royal king queen lead power gold supreme victory trophy dynamic majestic kingdom headwear",
  "🎓": "graduation cap university college school completed degree success smart education layout professional headwear",
  "🪖": "military helmet army headwear guard security fighter soldiers safety gear protection",
  "👕": "t-shirt shirt clothes clothing dress design casual cotton t-shirt top",
  "👔": "necktie shirt tie suit formal businessman business professional attire clothing",
  "👗": "dress clothing girls wedding party formal fashion boutique style wear apparel",
  "👟": "sneaker running shoe sports wear athletics gym fitness jogging apparel shoes",
  "🥾": "hiking boot brown boots climbing dynamic travel wilderness protection safety footwear shoe",
  "👓": "glasses tech reading specs smart eye optometrist nerd glasses clarity",
  "🕶️": "sunglasses cool chill shades dark vision style summer protection beach eyewear accessory",
  "🏁": "checkered flag racing finish speed win game standard race lines dynamic start track motor",
  "🚩": "red flag warning alert indicator mark landmark custom point checkpoint",
  "🏳️‍🌈": "rainbow flag pride LGBT community pride-flag flag tolerance equality peaceful stripes",
  "🏴‍☠️": "pirate flag skull bones crossbones black sea ship sailing sail captain warning Jolly Roger",
  "🎈": "balloon red float party birthday celebration congratulations bubbles toy helium kids",
  "🎉": "party popper celebration birthday confetti congrats fireworks success win cheer hooray",
  "🎊": "confetti ball golden party festival decoration congrats sparkle shine holiday celebrations",
  "🎁": "gift wrapped box present surprise birthday christmas celebration package ribbons bow",
  "🎀": "ribbon pink bow decoration accessory present gifts craft award beautiful layout",
  "🌠": "shooting star meteors night sky space cosmos galaxy wishes falling-star golden lucky core",
  "💥": "explosion spark collision boom strike smash blast target impact flash shock fire",
  "🚗": "car automobile red driving commute vehicle transport engine travel road trip traffic wheels",
  "🚕": "taxi cab yellow transportation driver ride passenger car vehicle commute auto transit",
  "🚙": "suv recreational vehicle blue jeep outdoor driving transport travel cross-country",
  "🚌": "bus schoolbus public transit terminal transport passengers route commute drive coach",
  "🚒": "fire engine truck red firefighters help rescue siren emergency water pump hazards safety",
  "🚓": "police car vehicle siren security law patrol cops alerts control highway alert-pin",
  "🛸": "flying saucer ufo alien space scifi transport galaxy sky mystery spaceship hover",
  "🚁": "helicopter chopper air flight transport pilot rotors sky flying rescue agency patrol",
  "✈️": "airplane plane flight travel airport aerospace trip skyways flying transport tourism pilot",
  "⛵": "sailboat boat yacht sea shipping sailing sail wind water sport travel marine",
  "⚓": "anchor navy marine ship safety harbor iron hook weight solid boat dock stability standard",
  "⚠️": "warning hazard danger sign caution yellow triangle attention alert safety priority error",
  "🛑": "stop sign red hex halt danger hazard warning street transit road rules",
  "☢️": "radioactive hazard danger yellow radiation bomb nuclear energy toxic chemistry safety alert",
  "☣️": "biohazard warning virus danger hazard infection biological pathology threat hospital medical security",
  "☯️": "yin yang balance zen lifestyle philosophy spiritual harmony peaceful meditation lifestyle taoism",
  "☮️": "peace sign symbol harmony love war-no-more hippy freedom layout peaceful",
  "💯": "hundred points score 100 excellent gold perfect victory best exam exam-paper success premium grade",
  "🛟": "ring buoy lifesaver rescue helper float marine boat water safety safeguard guard medical-buoy"
};

// Search descriptive tags context matching for emojis list
export function searchEmojis(query: string, category: string = "All", options: string[] = []): string[] {
  const normQuery = query.toLowerCase().trim();
  
  return options.filter((emoji) => {
    // 1. Is Category a match?
    if (category !== "All") {
      // Small helper checks
      const isSmileysCat = ["😀", "👋", "❤️"].some(e => emoji === e) || 
        // We'll fall back to checking if emoji has category match in container
        false; // Handled outside or here
    }
    
    // 2. Is Search Query match?
    if (!normQuery) return true;
    
    // Exact match
    if (emoji === normQuery) return true;
    
    // Check our keyword map
    const keywords = EMOJI_NAMES_MAP[emoji];
    if (keywords) {
      if (keywords.includes(normQuery)) return true;
    }
    
    return false;
  });
}
